### ISSUE TITLE
Trying to run under mac os and python 3.10

### ISSUE THREAD

**Issue by Thorbenl** [ChristopherGS/ultimate-fastapi-tutorial#41]
Not sure what im doing wrong, but after installing, and running `./prestart.sh`, i am getting the following error:
```python
Traceback (most recent call last):
  File "/Users/personal/ultimate-fastapi-tutorial/part-07-database/./app/backend_pre_start.py", line 3, in <module>
    from tenacity import after_log, before_log, retry, stop_after_attempt, wait_fixed
ModuleNotFoundError: No module named 'tenacity'
./prestart.sh: line 7: alembic: command not found
Traceback (most recent call last):
  File "/Users/personal/ultimate-fastapi-tutorial/part-07-database/./app/initial_data.py", line 3, in <module>
    from app.db.base import Base
ModuleNotFoundError: No module named 'app'
```

All i did was cloning the repo, going into one of the parts, and running poetry install.

**Comment by taikon** [comment]
Did you find a fix?
